config/routes.rb
Mkv::Application.routes.draw do
    
  root :to => 'home#index'
  
  match '/auth/:provider/callback' => 'sessions#create'

  match '/signout' => 'sessions#destroy', :as => :signout
  
  match '/success' => 'home#success'
  
  match '/share' => 'home#share'

  match '/signin' => 'sessions#new', :as => :signin
  
  match '/appathon' => 'home#appathon'

end

app/models/appathon.rb
class Appathon < ActiveRecord::Base
  attr_accessible :access_token, :fbid, :friends, :latitude, :longitude, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
    def self.create_with_omniauth(auth)
      create! do |user|
        user.provider = auth['provider']
        user.uid = auth['uid']
        if auth['info']
          user.name = auth['info']['name'] || ""
          user.email = auth['info']['email'] || ""
        end
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def success
    if session['fb_access_token']
        @graph = Koala::Facebook::API.new(session['fb_access_token'])
    
    else
        redirect_to root_url, :notice => 'Not sighned in'         
    end
  end
  
  def share
    @graph = Koala::Facebook::API.new(session['fb_access_token'])
    @graph.put_connections("me", "feed", :message => "Mkv app", :link => "http://mkv.herokuapp.com", :name => "Mkv", :description => "A social app integrating Facebook and Netflix")
    redirect_to root_url, :notice => 'Shared'
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
  		auth = request.env["omniauth.auth"]
          #data = "Full Name: "+ auth['info']['name'] + " || Email Id: "+ auth['info']['email']
          mssg = "Hi, "+ auth['info']['name'] + " Thanks for loggin into our website using facebook more interesting things will be happening soon !!!"
        session['fb_access_token'] = auth['credentials']['token']
        redirect_to success_url, :notice => mssg
	end
    
    def new
      redirect_to '/auth/facebook'
    end
    
    def destroy
      reset_session
      redirect_to root_url, :notice => 'Signed out'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<body class="homepage">

    	<!-- Header -->
			<div id="header">		
				<!-- Inner -->
					<div class="inner">
                        <p style="text-align:center;">
                            <ul>
                                <% flash.each do |key, msg| %>
                                  <%= content_tag :li, msg, id: key %>
                                <% end %>
                            </ul>
                        </p>
						<header>
							<h1><a href="#" id="logo">Mkv</a></h1>
							<hr />
							<span class="byline">A social app integrating Facebook and Netflix<br/>
                            </span>
						</header>
						<footer>
							<a href="#banner" class="button circled scrolly">↓ More ↓</a>
						</footer>
					</div>
			</div>
			
		<!-- Banner -->
			<div id="banner">
				<h2><%= link_to 'Sign in with Facebook', signin_path %></h2>
				<span class="byline">
					
				</span>
			</div>
		<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="12u">
							
							<!-- Contact -->
								<section class="contact">
									<ul class="icons">
										<li><a href="#" class="icon icon-github-sign"><span>Github</span></a></li>
										<li><a href="#" class="icon icon-facebook"><span>Facebook</span></a></li>
										<li><a href="#" class="icon icon-google-plus"><span>Google+</span></a></li>
										<li><a href="#" class="icon icon-linkedin"><span>Linkedin</span></a></li>
									</ul>
								</section>
							
							<!-- Copyright -->
								<div class="copyright">
									<ul class="menu">
										<li>&copy; mkv. All rights reserved.</li>
									</ul>
								</div>
							
						</div>
					
					</div>
				</div>
			</div>

	</body>

app/views/home/posting.html.erb
    <body class="no-sidebar">

    	<!-- Header -->
			<div id="header">

				<!-- Inner -->
					<div class="inner">
						<header>
							<h1><a href="#" id="logo">Mkv</a></h1>
						</header>
					</div>
				
				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="/">Home</a></li>
						</ul>
					</nav>

			</div>
			
		<!-- Main -->
			<div class="wrapper style1">

				<div class="container">
					<div class="row">
						<div class="12u skel-cell-mainContent" id="content">
							<hr />
							<article id="main" class="special">
								<header>
									<h2>Share Page</h2>
									<span class="byline">
									<ul>
                                        <% flash.each do |key, msg| %>
                                          <%= content_tag :li, msg, id: key %>
                                        <% end %>
                                    </ul>
                                      Share Somthing: <input type="text" id="fb_share_content" name="fb_share_content">
                                      <button id="share_btn">share</button>
                                      <label id="msg"></label>
                                    </br>
									</span>
								</header>
							</article>
						</div>
					</div>
				</div>

			</div>

		<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="12u">
							
							<!-- Contact -->
								<section class="contact">
									<ul class="icons">
										<li><a href="#" class="icon icon-github-sign"><span>Github</span></a></li>
										<li><a href="#" class="icon icon-facebook"><span>Facebook</span></a></li>
										<li><a href="#" class="icon icon-google-plus"><span>Google+</span></a></li>
										<li><a href="#" class="icon icon-linkedin"><span>Linkedin</span></a></li>
									</ul>
								</section>
							
							<!-- Copyright -->
								<div class="copyright">
									<ul class="menu">
										<li>&copy; mkv. All rights reserved.</li>
									</ul>
								</div>
							
						</div>
					
					</div>
				</div>
			</div>

	</body>
<script type="text/javascript">
  (function() {

    jQuery(function() {});


    $('body').prepend('<div id="fb-root"></div>');

    $.ajax({
      url: "" + window.location.protocol + "//connect.facebook.net/en_US/all.js",
      dataType: 'script',
      cache: true
    });

    window.fbAsyncInit = function() {
      FB.init({
        appId: '<%= Mkv::Application.config.app_id %>',
        cookie: true
      });

      $("#share_btn").click(function(){
        // calling the API ...
        var obj = {
          method: 'feed',
          link: 'http://mkv.herokuapp.com',
          picture: '',
          name: 'Mkv',
          caption: "Try Mkv",
          description: "A social app integrating Facebook and Netflix"
        };

        function callback(response) {
          document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
        }

        FB.ui(obj, callback);
      });

    };

  }).call(this);

</script>

app/views/home/success.html.erb
    <body class="no-sidebar">

		<!-- Header -->
			<div id="header">

				<!-- Inner -->
					<div class="inner">
						<header>
							<h1><a href="#" id="logo">Mkv</a></h1>
						</header>
					</div>
				
				<!-- Nav -->
					<nav id="nav">
						<ul>
							<li><a href="/">Home</a></li>
                            <li><a href="/signout">Sign Out</a></li>
						</ul>
					</nav>

			</div>
			
		<!-- Main -->
			<div class="wrapper style1">

				<div class="container">
					<div class="row">
						<div class="12u skel-cell-mainContent" id="content">
							<hr />
							<article id="main" class="special">
								<header>
									<h2>Success Page</h2>
									<span class="byline">
    									<ul>
                                            <% flash.each do |key, msg| %>
                                              <%= content_tag :li, msg, id: key %>
                                            <% end %>
                                        </ul><br/>
                                        <h3><%= session['fb_access_token'] %></h3><br/>
                                        <a class="button" href="/share">Share</a>
									</span>
								</header>
							</article>
						</div>
					</div>
				</div>

			</div>

		<!-- Footer -->
			<div id="footer">
				<div class="container">
					<div class="row">
						<div class="12u">
							
							<!-- Contact -->
								<section class="contact">
									<ul class="icons">
										<li><a href="#" class="icon icon-github-sign"><span>Github</span></a></li>
										<li><a href="#" class="icon icon-facebook"><span>Facebook</span></a></li>
										<li><a href="#" class="icon icon-google-plus"><span>Google+</span></a></li>
										<li><a href="#" class="icon icon-linkedin"><span>Linkedin</span></a></li>
									</ul>
								</section>
							
							<!-- Copyright -->
								<div class="copyright">
									<ul class="menu">
										<li>&copy; mkv. All rights reserved.</li>
									</ul>
								</div>
							
						</div>
					
					</div>
				</div>
			</div>

	</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mkv</title>
  <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <!--[if IE]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
	<script src="js/jquery.dropotron.js"></script>
	<script src="js/skel.min.js"></script>
	<script src="js/skel-panels.min.js"></script>
	<script src="js/init.js"></script>
	<link rel="stylesheet" href="css/skel-noscript.css" />
	<link rel="stylesheet" href="css/style.css" />
	<link rel="stylesheet" href="css/style-desktop.css" />
	<link rel="stylesheet" href="css/style-noscript.css" />
	<!--[if lte IE 8]><link rel="stylesheet" href="css/ie8.css" /><![endif]-->
  <%= csrf_meta_tags %>
</head>
<%= yield %>
</html>